name: Deploy Discord Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy code to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "~/discord-bot/"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/discord-bot
            
            # Create and activate virtual environment
            python3 -m venv venv
            source venv/bin/activate
            
            # Update pip and install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt
            
            # Stop existing process
            pkill -f main.py || true
            
            # Create or update systemd service
            sudo tee /etc/systemd/system/discord-bot.service << EOF
            [Unit]
            Description=Discord Bot Service
            After=network.target
            
            [Service]
            Type=simple
            User=${{ secrets.USERNAME }}
            WorkingDirectory=/home/${{ secrets.USERNAME }}/discord-bot
            Environment=PATH=/home/${{ secrets.USERNAME }}/discord-bot/venv/bin
            ExecStart=/home/${{ secrets.USERNAME }}/discord-bot/venv/bin/python3 main.py
            Restart=always
            
            [Install]
            WantedBy=multi-user.target
            EOF
            
            # Reload systemd and restart service
            sudo systemctl daemon-reload
            sudo systemctl enable discord-bot
            sudo systemctl restart discord-bot
