name: Deploy Discord Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy code to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "~/discord-bot/"

      - name: Setup Python Environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/discord-bot
            echo "Setting up Python environment..."
            python3 -m venv venv
            source venv/bin/activate
            echo "Upgrading pip..."
            pip install --upgrade pip
            echo "Installing dependencies..."
            pip install -r requirements.txt
            echo "Environment setup complete"

      - name: Create and Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Stopping existing process..."
            pkill -f main.py || true
            
            echo "Creating systemd service file..."
            cat << EOF | sudo tee /etc/systemd/system/discord-bot.service
            [Unit]
            Description=Discord Bot Service
            After=network.target
            
            [Service]
            Type=simple
            User=${{ secrets.USERNAME }}
            WorkingDirectory=/home/${{ secrets.USERNAME }}/discord-bot
            Environment=PATH=/home/${{ secrets.USERNAME }}/discord-bot/venv/bin
            ExecStart=/home/${{ secrets.USERNAME }}/discord-bot/venv/bin/python3 main.py
            Restart=always
            RestartSec=5
            StandardOutput=append:/home/${{ secrets.USERNAME }}/discord-bot/bot.log
            StandardError=append:/home/${{ secrets.USERNAME }}/discord-bot/bot.error.log
            
            [Install]
            WantedBy=multi-user.target
            EOF
            
            echo "Reloading systemd..."
            sudo systemctl daemon-reload
            
            echo "Enabling service..."
            sudo systemctl enable discord-bot
            
            echo "Starting service..."
            sudo systemctl restart discord-bot
            
            echo "Checking service status..."
            sudo systemctl status discord-bot --no-pager
            
            echo "Checking logs..."
            tail -n 50 /home/${{ secrets.USERNAME }}/discord-bot/bot.log || true
            tail -n 50 /home/${{ secrets.USERNAME }}/discord-bot/bot.error.log || true
