name: Deploy Discord Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy code to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "~/discord-bot/"

      - name: Setup Python environment and run bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.PORT }}
          script: |
            pkill -f main.py || false
            cd ~/discord-bot
            echo "Setting up Python environment..."
            python3 -m venv venv
            source venv/bin/activate
            echo "Upgrading pip..."
            pip install --upgrade pip
            echo "Installing dependencies..."
            pip install -r requirements.txt
            echo "Environment setup complete"
            python3 main.py
