name: Deploy Discord Bot
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Copy code to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "~/discord-bot/"
      - name: Setup Python environment and run bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/discord-bot
            
            # Проверяем существование screen сессии и закрываем её
            if screen -list | grep -q "discord-bot"; then
              screen -S discord-bot -X quit
            fi
            
            echo "Setting up Python environment..."
            python3 -m venv venv
            source venv/bin/activate
            echo "Upgrading pip..."
            pip install --upgrade pip
            echo "Installing dependencies..."
            pip install -r requirements.txt
            echo "Environment setup complete"
            
            # Запускаем бота в новой screen сессии
            screen -dmS discord-bot bash -c "cd ~/discord-bot && source venv/bin/activate && python3 main.py"
            
            # Проверяем, что сессия создалась успешно
            if screen -list | grep -q "discord-bot"; then
              echo "Bot successfully started in screen session"
            else
              echo "Failed to start bot in screen session"
              exit 1
            fi
