name: Deploy Discord Bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy code to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "~/discord-bot/"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASS }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          timeout: 1200
          script: |
            # Перейти в директорию проекта
            cd ~/discord-bot

            # Убедиться, что зависимости обновлены
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            # Остановить текущий процесс, если он работает
            pkill -f main.py || true

            # Запустить новый процесс
            nohup python3 main.py > bot.log 2>&1 &
